
file(GLOB PP_TESTS ${CMAKE_CURRENT_SOURCE_DIR}/test_*.h)


set_source_files_properties(${PP_TESTS} LANGUAGE CXX)


include_directories(${CMAKE_SOURCE_DIR})

set(TEST_GENERATOR_BIN ${CMAKE_SOURCE_DIR}/tools/test_generator.py)
set(TEST_MAIN_FILENAME ${CMAKE_CURRENT_BINARY_DIR}/main.cpp)

ADD_CUSTOM_COMMAND(
    OUTPUT ${TEST_MAIN_FILENAME}
    COMMAND ${TEST_GENERATOR_BIN} --output ${TEST_MAIN_FILENAME} ${PP_TESTS}
    DEPENDS ${PP_TESTS} ${TEST_GENERATOR_BIN}
)

message(${PP_TESTS})

add_executable(tests ${TEST_SOURCES} ${TEST_MAIN_FILENAME} ${PP_TESTS} ${CMAKE_CURRENT_SOURCE_DIR}/picophysics.c)
